# FROM node:20-alpine
FROM oven/bun:1-alpine

RUN addgroup -g 1001 -S nextjs && \
    adduser -S nextjs -u 1001 -G nextjs

WORKDIR /app

COPY --chown=nextjs:nextjs next.config.mjs package.json package-lock.json* ./

RUN npm install

COPY --chown=nextjs:nextjs . .

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "dev"]
