---
name: Basic Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test-git-clone-on-windows:
    timeout-minutes: 5
    name: 'Test git clone on Windows'
    runs-on: ['windows-latest']
    steps:
      - name: 'Checkout ${{ github.ref }} ( ${{ github.sha }} )'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          persist-credentials: false
