---
# https://github.com/j178/prek
name: Standard hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  prek-standard:
    uses: ./.github/workflows/reusable-prek.yml
    with:
      skip_hooks: 'yamllint'
      extra_args: '--all-files --verbose'
