---
# https://github.com/j178/prek
name: Audit hooks

on: [pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: j178/prek-action@79f765515bd648eb4d6bb1b17277b7cb22cb6468 # v2.0.0
        with:
          install-only: true
      - name: Run audit pre-commit hooks
        run: prek run --config .pre-commit-config-audit.yaml --all-files --show-diff-on-failure
