---
# https://github.com/j178/prek
name: Standard hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions: {}

jobs:
  prek-macos:
    name: Standard hooks (macos-latest)
    uses: ./.github/workflows/reusable-prek-standard.yml
    with:
      os: macos-latest

  prek-ubuntu:
    name: Standard hooks (ubuntu-latest)
    uses: ./.github/workflows/reusable-prek-standard.yml
    with:
      os: ubuntu-latest

  prek-windows:
    name: Standard hooks (windows-latest)
    uses: ./.github/workflows/reusable-prek-standard.yml
    with:
      os: windows-latest
