---
# https://github.com/j178/prek
name: Manual hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  prek-macos:
    name: Manual hooks (macos-latest)
    uses: ./.github/workflows/reusable-prek-manual.yml
    with:
      os: macos-latest

  prek-ubuntu:
    name: Manual hooks (ubuntu-latest)
    uses: ./.github/workflows/reusable-prek-manual.yml
    with:
      os: ubuntu-latest
