---
# Reusable workflow: run manual prek hooks
# https://github.com/j178/prek
name: Reusable – Manual prek hooks

on:
  workflow_call:
    inputs:
      os:
        description: 'Runner OS to use'
        type: string
        required: false
        default: 'ubuntu-latest'

permissions: {}

jobs:
  prek:
    name: 🏃🏼 prek manual on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2.0.2
        with:
          install-only: true
      - name: Run manual prek hooks
        run: prek run --all-files --color=always --hook-stage manual --show-diff-on-failure
